project_id = "rpbkilhzulaugzrlatts"

[functions.tests-crud]
verify_jwt = false

[functions.parse-prescription]
verify_jwt = false

[functions.extract-report]
verify_jwt = false

[functions.reverify-abnormals]
verify_jwt = false

[functions.process-report-queue]
verify_jwt = false

[functions.direct-ai-extract]
verify_jwt = false
